!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: h
!   with respect to varying inputs: p x
!   RW status of diff variables: h:out p:in x:in
! Landau
SUBROUTINE HFUN_D(x, xd, p, pd, c, h, hd)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x(2), p(2), c(4)
  DOUBLE PRECISION, INTENT(IN) :: xd(2), pd(2)
  DOUBLE PRECISION, INTENT(OUT) :: h
  DOUBLE PRECISION, INTENT(OUT) :: hd
! local variables
  DOUBLE PRECISION :: r, th, pr, pth
  DOUBLE PRECISION :: rd, thd, prd, pthd
  DOUBLE PRECISION :: m2, a, g1, g2, g3, cr, sr, ct, st, mu1, mu2
  DOUBLE PRECISION :: m2d, crd, srd, ctd, std, mu1d, mu2d
  INTRINSIC COS
  INTRINSIC SIN
  INTRINSIC SQRT
  DOUBLE PRECISION :: arg1
  DOUBLE PRECISION :: arg1d
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1d
  rd = xd(1)
  r = x(1)
  thd = xd(2)
  th = x(2)
  prd = pd(1)
  pr = p(1)
  pthd = pd(2)
  pth = p(2)
  crd = -(rd*SIN(r))
  cr = COS(r)
  srd = rd*COS(r)
  sr = SIN(r)
  ctd = -(thd*SIN(th))
  ct = COS(th)
  std = thd*COS(th)
  st = SIN(th)
  g1 = c(1)
  g2 = c(2)
  g3 = c(3)
  a = c(4)
  mu1d = a*g1*(crd*sr+cr*srd) + (g2-g3)*((ctd*st+ct*std)*sr+ct*st*srd) -&
&   a*((g2*2*ct*ctd+g3*2*st*std)*cr*sr+(g2*ct**2+g3*st**2)*(crd*sr+cr*&
&   srd))
  mu1 = a*g1*cr*sr + (g2-g3)*ct*st*sr - a*(g2*ct**2+g3*st**2)*cr*sr
  mu2d = a*(g2-g3)*(ctd*st+ct*std) - g1*crd + (g3*2*st*std+g2*2*ct*ctd)*&
&   cr + (g3*st**2+g2*ct**2)*crd
  mu2 = a*(g2-g3)*ct*st - g1*cr + (g3*st**2+g2*ct**2)*cr
  m2d = 2*SIN(r)*rd*COS(r)
  m2 = SIN(r)**2
  arg1d = 2*pr*prd + (2*pth*pthd*m2-pth**2*m2d)/m2**2
  arg1 = pr**2 + pth**2/m2
  IF (arg1 .EQ. 0.0) THEN
    result1d = 0.D0
  ELSE
    result1d = arg1d/(2.0*SQRT(arg1))
  END IF
  result1 = SQRT(arg1)
  hd = mu1d*pr + mu1*prd + mu2d*pth + mu2*pthd + result1d
  h = mu1*pr + mu2*pth + result1
END SUBROUTINE HFUN_D

