!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun_d in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: hd
!   with respect to varying inputs: p x
!   RW status of diff variables: p:in x:in hd:out
!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.8 (r4996) - 25 Oct 2013 15:08
!
!  Differentiation of hfun in forward (tangent) mode (with options fixinterface):
!   variations   of useful results: h
!   with respect to varying inputs: p x
!   RW status of diff variables: h:out p:in x:in
! Landau
SUBROUTINE HFUN_D_D(x, xd0, xd, p, pd0, pd, c, h, hd, hdd)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: x(2), p(2), c(4)
  DOUBLE PRECISION, INTENT(IN) :: xd0(2), pd0(2)
  DOUBLE PRECISION, INTENT(IN) :: xd(2), pd(2)
  DOUBLE PRECISION, INTENT(OUT) :: h
  DOUBLE PRECISION, INTENT(OUT) :: hd
  DOUBLE PRECISION, INTENT(OUT) :: hdd
! local variables
  DOUBLE PRECISION :: r, th, pr, pth
  DOUBLE PRECISION :: rd0, thd0, prd0, pthd0
  DOUBLE PRECISION :: rd, thd, prd, pthd
  DOUBLE PRECISION :: m2, a, g1, g2, g3, cr, sr, ct, st, mu1, mu2
  DOUBLE PRECISION :: m2d0, crd0, srd0, ctd0, std0, mu1d0, mu2d0
  DOUBLE PRECISION :: m2d, crd, srd, ctd, std, mu1d, mu2d
  DOUBLE PRECISION :: m2dd, crdd, srdd, ctdd, stdd, mu1dd, mu2dd
  INTRINSIC COS
  INTRINSIC SIN
  INTRINSIC SQRT
  DOUBLE PRECISION :: arg1
  DOUBLE PRECISION :: arg1d0
  DOUBLE PRECISION :: arg1d
  DOUBLE PRECISION :: arg1dd
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1d
  DOUBLE PRECISION :: result1dd
  DOUBLE PRECISION :: result10
  DOUBLE PRECISION :: result10d
  rd = xd(1)
  rd0 = xd0(1)
  r = x(1)
  thd = xd(2)
  thd0 = xd0(2)
  th = x(2)
  prd = pd(1)
  prd0 = pd0(1)
  pr = p(1)
  pthd = pd(2)
  pthd0 = pd0(2)
  pth = p(2)
  crdd = -(rd*rd0*COS(r))
  crd = -(rd*SIN(r))
  crd0 = -(rd0*SIN(r))
  cr = COS(r)
  srdd = -(rd*rd0*SIN(r))
  srd = rd*COS(r)
  srd0 = rd0*COS(r)
  sr = SIN(r)
  ctdd = -(thd*thd0*COS(th))
  ctd = -(thd*SIN(th))
  ctd0 = -(thd0*SIN(th))
  ct = COS(th)
  stdd = -(thd*thd0*SIN(th))
  std = thd*COS(th)
  std0 = thd0*COS(th)
  st = SIN(th)
  g1 = c(1)
  g2 = c(2)
  g3 = c(3)
  a = c(4)
  mu1dd = a*g1*(crdd*sr+crd*srd0+crd0*srd+cr*srdd) + (g2-g3)*((ctdd*st+&
&   ctd*std0+ctd0*std+ct*stdd)*sr+(ctd*st+ct*std)*srd0+(ctd0*st+ct*std0)&
&   *srd+ct*st*srdd) - a*((g2*2*(ctd0*ctd+ct*ctdd)+g3*2*(std0*std+st*&
&   stdd))*cr*sr+(g2*2*ct*ctd+g3*2*st*std)*(crd0*sr+cr*srd0)+(g2*2*ct*&
&   ctd0+g3*2*st*std0)*(crd*sr+cr*srd)+(g2*ct**2+g3*st**2)*(crdd*sr+crd*&
&   srd0+crd0*srd+cr*srdd))
  mu1d = a*g1*(crd*sr+cr*srd) + (g2-g3)*((ctd*st+ct*std)*sr+ct*st*srd) -&
&   a*((g2*2*ct*ctd+g3*2*st*std)*cr*sr+(g2*ct**2+g3*st**2)*(crd*sr+cr*&
&   srd))
  mu1d0 = a*g1*(crd0*sr+cr*srd0) + (g2-g3)*((ctd0*st+ct*std0)*sr+ct*st*&
&   srd0) - a*((g2*2*ct*ctd0+g3*2*st*std0)*cr*sr+(g2*ct**2+g3*st**2)*(&
&   crd0*sr+cr*srd0))
  mu1 = a*g1*cr*sr + (g2-g3)*ct*st*sr - a*(g2*ct**2+g3*st**2)*cr*sr
  mu2dd = a*(g2-g3)*(ctdd*st+ctd*std0+ctd0*std+ct*stdd) - g1*crdd + (g3*&
&   2*(std0*std+st*stdd)+g2*2*(ctd0*ctd+ct*ctdd))*cr + (g3*2*st*std+g2*2&
&   *ct*ctd)*crd0 + (g3*2*st*std0+g2*2*ct*ctd0)*crd + (g3*st**2+g2*ct**2&
&   )*crdd
  mu2d = a*(g2-g3)*(ctd*st+ct*std) - g1*crd + (g3*2*st*std+g2*2*ct*ctd)*&
&   cr + (g3*st**2+g2*ct**2)*crd
  mu2d0 = a*(g2-g3)*(ctd0*st+ct*std0) - g1*crd0 + (g3*2*st*std0+g2*2*ct*&
&   ctd0)*cr + (g3*st**2+g2*ct**2)*crd0
  mu2 = a*(g2-g3)*ct*st - g1*cr + (g3*st**2+g2*ct**2)*cr
  m2dd = 2*rd*(rd0*COS(r)**2-SIN(r)**2*rd0)
  m2d = 2*SIN(r)*rd*COS(r)
  m2d0 = 2*SIN(r)*rd0*COS(r)
  m2 = SIN(r)**2
  arg1dd = 2*prd*prd0 + ((2*pthd*(pthd0*m2+pth*m2d0)-2*pth*pthd0*m2d-pth&
&   **2*m2dd)*m2**2-(2*pth*pthd*m2-pth**2*m2d)*2*m2*m2d0)/(m2**2)**2
  arg1d = 2*pr*prd + (2*pth*pthd*m2-pth**2*m2d)/m2**2
  arg1d0 = 2*pr*prd0 + (2*pth*pthd0*m2-pth**2*m2d0)/m2**2
  arg1 = pr**2 + pth**2/m2
  IF (arg1 .EQ. 0.0) THEN
    result1d = 0.d0
    result1dd = 0.D0
  ELSE
    IF (arg1 .EQ. 0.0) THEN
      result10d = 0.D0
    ELSE
      result10d = arg1d0/(2.0*SQRT(arg1))
    END IF
    result10 = SQRT(arg1)
    result1dd = (arg1dd*2.0*result10-arg1d*2.0*result10d)/(2.0*result10)&
&     **2
    result1d = arg1d/(2.0*result10)
  END IF
  result1 = SQRT(arg1)
  hdd = mu1dd*pr + mu1d*prd0 + prd*mu1d0 + mu2dd*pth + mu2d*pthd0 + pthd&
&   *mu2d0 + result1dd
  hd = mu1d*pr + mu1*prd + mu2d*pth + mu2*pthd + result1d
  h = mu1*pr + mu2*pth + result1
END SUBROUTINE HFUN_D_D

